spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: your_username
    password: your_password
  oauth2:
    client:
      registration:
        github:
          client-id: your_github_client_id
          client-secret: your_github_client_secret
          scope: user:email
      provider:
        github:
          authorization-uri: https://github.com/login/oauth/authorize
          token-uri: https://github.com/login/oauth/access_token
          user-info-uri: https://api.github.com/user
